---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "ZHB's Dashboard"
subtitle: "Homepage"
logo: "favicon.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optionnal theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Welcome !"
  content: "This is the Navigation Page for ZHB's web services."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/gkzhb"
    target: "_blank" # optionnal html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://wiki.gkzhb.top/"
    target: "_blank"
  - name: "Blog"
    icon: "fa fa-edit"
    url: "https://blog.gkzhb.top/"
    target: "_blank"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Content Information"
    icon: "fas fa-info"
    items:
      - name: "Doku Wiki"
        logo: "assets/tools/dokuwiki.png"
        subtitle: "Personal Wiki"
        url: "https://wiki.gkzhb.top"
        tag: "info"
        target: "_blank"
      - name: "LeanNote"
        logo: "assets/tools/leanote.png"
        subtitle: "Note App"
        url: "https://note.gkzhb.top"
        tag: "info"
        target: "_blank"
      - name: "Tiny Tiny RSS"
        logo: "assets/tools/ttrss.png"
        subtitle: "RSS Reader"
        url: "https://reader.gkzhb.top/"
        tag: "app"
        target: "_blank"
      - name: "Miniflux"
        logo: "assets/tools/miniflux.svg"
        subtitle: "Very Simple RSS Reader"
        url: "https://miniflux.gkzhb.top/"
        tag: "app"
        target: "_blank"
      - name: "Wallabag"
        logo: "assets/tools/wallabag.svg"
        subtitle: "Read It Later"
        url: "https://wallabag.gkzhb.top/"
        tag: "app"
        target: "_blank"
      - name: "Huginn"
        logo: "assets/tools/huginn.png"
        subtitle: "Web Automation"
        url: "https://huginn.gkzhb.top/"
        tag: "app"
        target: "_blank"
  - name: "Code"
    icon: "fa fa-code"
    items:
      - name: "Jenkins"
        logo: "assets/tools/jenkins.svg"
        subtitle: "Continuous integration server"
        url: "https://ci.gkzhb.top/"
        tag: "CI"
        target: "_blank"
      - name: "JupyterHub"
        logo: "assets/tools/jupyter.svg"
        subtitle: "Jupyter Notebook"
        url: "https://jupyter.gkzhb.top/"
        tag: "code"
        target: "_blank"
  - name: "Cloud Storage"
    icon: "fas fa-cloud"
    items:
      - name: "Seafile"
        logo: "assets/tools/seafile.png"
        # subtitle: "Continuous integration server"
        url: "https://seafile.gkzhb.top/"
        tag: "cloud"
      - name: "Nextcloud"
        logo: "assets/tools/nextcloud.png"
        subtitle: "Need IPv6 Support to Access"
        tag: "cloud"
        url: "https://nextcloud.gkzhb.top"
        target: "_blank" # optionnal html a tag target attribute
  - name: "Games"
    icon: "fas fa-gamepad"
    items:
      - name: "MCSM"
        logo: "assets/tools/chest.png"
        subtitle: "Minecraft Server Manager"
        url: "https://mc.gkzhb.top/"
        tag: "game"
